Created Cart Components, actions, and reducer
FullstackAcademy/2007-try-ceratopses pull request #26
Opened 2020-11-03 14:05 UTC by rtaha07

1) user can add items to cart, remove items from cart, edit/remove quantities of items in the cart, and  automatically calculate the total price and total number of products in the cart.

2020-11-03 14:20 UTC, ysolovyova123 commented on client/App.js
> +        <Route path="/cart/:id" component={Cart} exact />
what is the difference between lines 33 and line 34, shouldn't the path just to be to "/cart"?

2020-11-03 14:30 UTC, ysolovyova123 commented on client/store/cart.js
> +import cartItems from '../../server/db/cartSeed';
cart items should be a thunk getting cart items, not a db seed

2020-11-03 14:31 UTC, ysolovyova123 commented on client/store/cart.js
> +  cart: cartItems,
cart items should be a thunk (axios call) to get a user's cart items, not a db seed

2020-11-03 14:33 UTC, ysolovyova123 commented on client/store/cart.js
> +        el = { ...el, amount: el.amount - 1 };
can we change the naming here from amount to quantity? amount is typically $ amount, qty is # of items. may make things a little more confusing down the line.

2020-11-03 15:34 UTC, ysolovyova123 requested changes
please see the comments

2020-11-03 15:34 UTC, ysolovyova123 commented on client/store/cart.js
> +  // if (action.type === CART_SAVE_CHECKOUT) {
remove these if not using

2020-11-03 15:34 UTC, ysolovyova123 commented on client/components/Cart/CartContainer.js
> +  useEffect(() => {
what do lines 14-16 do? aren't you pulling in cart items, total and dispatch from the store in line 13?

2020-11-03 15:34 UTC, ysolovyova123 commented on client/components/Cart/CartItem.js
> +        <Link className="item-title" to={'/products/' + cartItems.title}>
I don't believe we have a route for '/products/item.title', did you mean 'products/item.id'?

2020-11-03 15:34 UTC, ysolovyova123 commented on client/components/Cart/CartItem.js
> +  const { id, amount } = props;
where are these props getting pulled in from?are the props (id, amount) for the particular item we are rendering here, and they change per item rendered?

2020-11-03 15:34 UTC, ysolovyova123 commented on client/components/Cart/CartNav.js
> +            <path d="M16 6v2h2l2 12H0L2 8h2V6a6 6 0 1 1 12 0zm-2 0a4 4 0 1 0-8 0v2h8V6zM4 10v2h2v-2H4zm10 0v2h2v-2h-2z" />
what is this?

2020-11-03 15:34 UTC, ysolovyova123 commented on server/db/cartSeed.js
> +const image2Url = '../../images/flowers2.jpg';
what is this seed file for? we should not be seeding anything to the cart.... products should be added to cart from the products page (from db orders > order items table) via axios calls. It looks like all cart order items are currently being pulled in from this seed file rather than from the products page.

2020-11-03 15:34 UTC, ysolovyova123 commented on client/components/CategoryProducts.js
> +import { getProducts } from '../store/store';
I don't see this in the store. Wrong link

2020-11-03 15:34 UTC, ysolovyova123 commented on client/components/Navbar/index.js
>                  <NavLogo to="/" onClick={this.toggleHome}>
in the below, where is the LogOut button?

2020-11-03 15:34 UTC, ysolovyova123 commented on client/components/Profile/index.js
> +        <h1> Profile page content goes here - testing component</h1>
this component is out of date - please pull from the dev branch and merge conflicts to see the updated component, otherwise we will lose the current edits. This should be done for the rest of the components as well to make sure this code is up-to-date with the most recent code in dev.

2020-11-03 16:44 UTC, rtaha07 commented on client/App.js
> +        <Route path="/cart/:id" component={Cart} exact />
I used the one in line 33 for the cart component, but I thought we may later need to have separate carts for guests and registered users, so I added line 34

2020-11-03 17:02 UTC, rtaha07 commented on client/store/cart.js
> +  cart: cartItems,
Yes, I know that; at the beginning I had a thunk as addToCart but it did't work as I expected, so I decided for now to have a small seed file as a test and to make sure all the functionality are working as I expected and later I will add the thunk with axios call. I just wanted my code to be part of the coming code review.

2020-11-03 17:14 UTC, rtaha07 commented on client/store/cart.js
> +  // if (action.type === CART_SAVE_CHECKOUT) {
This code is not the final one for the cart. We still need to add more functionality, especially related to checkout and payment. I put them as comments because I couldn't finish them and planning on working on them later.

2020-11-03 17:36 UTC, rtaha07 commented on client/components/Cart/CartContainer.js
> +  useEffect(() => {
Yes. But this part is re-rendering every time something changes in cart (ex total and amount(qty)); since we ran useEffect after each re-rendering, we will dispatch GET_TOTALS & calculate the total and amount , and then updating the cart. This is not only calculating individual product's qty in the cart but also the qty of all products in cart, which appears in the upper right side of the cartNav.

2020-11-03 17:37 UTC, rtaha07 commented on client/components/Cart/CartItem.js
> +        <Link className="item-title" to={'/products/' + cartItems.title}>
That's ok. I can change it later.

2020-11-03 17:49 UTC, rtaha07 commented on client/components/Cart/CartItem.js
> +  const { id, amount } = props;
Yes, these props are the items properties. They have been passed from the CartContainer component through the map function and the spread operator.

2020-11-03 17:51 UTC, rtaha07 commented on client/components/Cart/CartNav.js
> +            <path d="M16 6v2h2l2 12H0L2 8h2V6a6 6 0 1 1 12 0zm-2 0a4 4 0 1 0-8 0v2h8V6zM4 10v2h2v-2H4zm10 0v2h2v-2h-2z" />
This is the shopping cart image/icon in the upper right side of cart nav.

2020-11-03 17:59 UTC, rtaha07 commented on server/db/cartSeed.js
> +const image2Url = '../../images/flowers2.jpg';
As I said before. I made this file to only test my code and I will delete it later after adding the thunk.

2020-11-03 18:01 UTC, rtaha07 commented on client/components/CategoryProducts.js
> +import { getProducts } from '../store/store';
I have no idea. This is not part of my code.

2020-11-03 18:07 UTC, rtaha07 commented on client/components/Navbar/index.js
>                  <NavLogo to="/" onClick={this.toggleHome}>
LogOut button was not part of my Navbar code, I only did Login and Signup.

2020-11-03 18:18 UTC, rtaha07 commented on client/components/Profile/index.js
> +        <h1> Profile page content goes here - testing component</h1>
I always pull from the dev before starting working in a new branch and again before pushing back to gitHub. Today also I made sure that was up-to-date with dev. There were couple of merge conflicts and I resolved them before pushing it to gitHub. For this component specifically, there were two separate components with the same name, so I merged them together to prevent duplicates. I didn't delete or change any of their code because it wasn't mine.

2020-11-03 18:20 UTC, rtaha07 commented on client/store/cart.js
> +import cartItems from '../../server/db/cartSeed';
see the next comment.

2020-11-03 18:23 UTC, rtaha07 commented
> please see the comments

Thanks Katerina for the feedback!

2020-11-03 18:31 UTC, rtaha07 commented on client/store/cart.js
> +        el = { ...el, amount: el.amount - 1 };
Oh, sure. I will do that!

2020-11-03 18:55 UTC, garber34 commented on client/components/SignIn/index.js
> +>>>>>>> 2064fc29a86d482dc290ed0a23ea4f9a5a3bdf4d
there's unresolved merge conflict here prevent. which is the correct version?

2020-11-03 18:58 UTC, garber34 commented on client/components/SignIn/SignIn.js
> +import React from 'react';
what's the difference between SignIn/SignIn.js and SignIn/index.js?

2020-11-03 19:01 UTC, garber34 commented on client/App.js
> +        <Route path="/cart/:id" component={Cart} exact />
i would get rid of line 34 until we need it

2020-11-03 19:02 UTC, garber34 commented on client/store/cart.js
> +import cartItems from '../../server/db/cartSeed';
> cart items should be a thunk (axios call) to get a user's cart items, not a db seed

agreed

2020-11-03 19:03 UTC, garber34 commented on client/store/cart.js
> +  cart: cartItems,
i don't think this is ready to be merged if the thunk isn't working

2020-11-03 19:07 UTC, garber34 commented on client/store/cart.js
> +  // if (action.type === CART_SAVE_CHECKOUT) {
> This code is not the final one for the cart. We still need to add more functionality, especially related to checkout and payment. I put them as comments because I couldn't finish them and planning on working on them later.

if they aren't working yet, then push up a version without them then work on them as a separate branch

2020-11-03 19:17 UTC, garber34 commented on client/components/Cart/CartItem.js
> +        <Link className="item-title" to={'/products/' + cartItems.title}>
> That's ok. I can change it later.

you should change it now to avoid any bugs when merging

2020-11-03 19:22 UTC, garber34 commented on server/db/cartSeed.js
> +const image2Url = '../../images/flowers2.jpg';
the thunk should get added before merging to dev

2020-11-03 19:23 UTC, garber34 requested changes
see comments

2020-11-03 20:23 UTC, ysolovyova123 commented on client/App.js
> +        <Route path="/cart/:id" component={Cart} exact />
^ agreed

2020-11-03 20:24 UTC, ysolovyova123 commented on client/store/cart.js
> +  cart: cartItems,
agreed. i'm glad the functionality is proven to work, but we need this now to hook up to axios calls / the actual data, not the seed file, before merging to dev.

2020-11-03 20:25 UTC, ysolovyova123 commented on client/store/cart.js
> +        el = { ...el, amount: el.amount - 1 };
thank you!

2020-11-03 20:26 UTC, ysolovyova123 commented on client/components/CategoryProducts.js
> +import { getProducts } from '../store/store';
i would pull from what's in the dev branch and merge so that you can resolve any conflicts your code may have with what's in dev - this will also pull in the updated code, this looks like it's out of date.

2020-11-03 20:26 UTC, ysolovyova123 commented on client/components/Navbar/index.js
>                  <NavLogo to="/" onClick={this.toggleHome}>
please pull from the dev branch and merge into yours to get the most up-to-date code.

2020-11-06 02:49 UTC, garber34 commented
closing pull request, use cart branch instead

2020-11-06 02:49 UTC, closed without merging