User profiles
FullstackAcademy/2007-try-ceratopses pull request #28
Opened 2020-11-04 05:19 UTC by garber34

Logged in users can see and edit their own profile information, with order and review histories. And the styling is a little nicer.

2020-11-04 22:33 UTC, ysolovyova123 commented on client/components/SingleUser.js
>    ///these should get split into components
what is the difference between this and the Profile/Index.js component?

2020-11-04 22:35 UTC, ysolovyova123 commented on client/components/UserManagement.js
> +        <div id="usersList" className="scrollable">
what does className="scrollable" do?

2020-11-04 22:39 UTC, ysolovyova123 commented on client/store/user.js
>  const UPDATE_USER = "UPDATE_USER";
the delete thunk, etc. should go in store/users not store/user. here the user in the store is anyone who is logged in.

2020-11-04 22:41 UTC, ysolovyova123 requested changes
please see the comments

2020-11-05 02:26 UTC, garber34 commented on client/components/SingleUser.js
>    ///these should get split into components
This one is for admins. Profile/index is based on it but call they are based on different parts of the store and hit different routes when making axios calls. and the edit priveleges are slightly different (users can't make themselves admins)

2020-11-05 02:28 UTC, garber34 commented on client/components/UserManagement.js
> +        <div id="usersList" className="scrollable">
it's for css styling that adds a scrollbar to the div when the contents overflow the height

2020-11-05 02:31 UTC, garber34 commented on client/store/user.js
>  const UPDATE_USER = "UPDATE_USER";
exactly. if the user deletes their account, then their account info needs to get deleted from the database, and the user state needs to be cleared, since there is no account to be logged in anymore.  store/users also has a delete thunk that deletes them from the database, and from the list of users state that only gets populated and is accessible when navigating to the admin section.

2020-11-05 17:12 UTC, ysolovyova123 commented on client/store/user.js
> +            dispatch(_deleteUser(userId))
remove userId here as it's not getting passed into the action creator.

2020-11-05 17:12 UTC, ysolovyova123 approved these changes

2020-11-05 17:12 UTC, merged